#!/bin/sh

set -e

REPO_ROOT_DIR=$(dirname "$SCRIPT")
TARGET_DIR=$REPO_ROOT_DIR/target

STAGE3_DIR=/var/stage3
CASCADE_DIR=/var/cascade
HD_PATH=$TARGET_DIR/kernel-hd

if [ ! -f $TARGET_DIR/rootfs.tar.gz ]; then
  mkdir -p $TARGET_DIR
  URL=https://distfiles.gentoo.org/releases/amd64/autobuilds/20240602T164858Z/stage3-amd64-openrc-20240602T164858Z.tar.xz
  wget -O $TARGET_DIR/rootfs.tar.gz $URL
  unset URL
fi
if [ ! -d $STAGE3_DIR/bin ]; then
  mkdir -p $STAGE3_DIR
  tar xpf $TARGET_DIR/rootfs.tar.gz --xattrs-include='*.*' --numeric-owner -C $STAGE3_DIR

  echo "nameserver 8.8.8.8" > $STAGE3_DIR/etc/resolv.conf
  
  mount --rbind /dev $STAGE3_DIR/dev
  mount --make-rslave $STAGE3_DIR/dev
  mount -t proc /proc $STAGE3_DIR/proc
  mount --rbind /sys $STAGE3_DIR/sys
  mount --make-rslave $STAGE3_DIR/sys
  # We just use a regular directory for /tmp
  # and delete it below.
  #
  # This doesn't align with the Gentoo guide
  # but it seems to work.
  mkdir -p /tmp
  # Gentoo docs specifying mounting /run, but
  # we skip that because configs end up being
  # saved here and we want to copy it to the
  # final disk image, so we don't want anything
  # from the underlying host machine included.

  # Copy in the Cascade ebuild repo
  #
  # For now we put this in tmp because we need
  # to first create the local repo and then
  # copy these in with the appropriate permissions.
  cp -r ebuild $STAGE3_DIR/tmp/
  
  echo "
  #!/bin/sh

  set -e

  # Really we should uncomment this rather than
  # add a new line..
  echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
  locale-gen
  
  # This assumes that there aren't any other USE flags
  # set by default.
  echo 'USE="dracut"' >> /etc/portage/make.conf
  echo 'ACCEPT_KEYWORDS="~amd64"' >> /etc/portage/make.conf
  echo 'ACCEPT_LICENSE="*"' >> /etc/portage/make.conf

  emerge-webrsync
  source /etc/profile

  # Add a local repository
  emerge app-eselect/eselect-repository
  eselect repository create cascade
  mv /tmp/ebuild/* /var/db/repos/cascade
  rm -r /tmp/ebuild
  chown -R portage:portage /var/db/repos/cascade

  # Install our patched version of xattr, so it doesn't attempt
  # to follow symlinks and break uutils coreutils.
  emerge --update sys-apps/install-xattr::cascade

  emerge --update sys-apps/coreutils::cascade
  " > $STAGE3_DIR/setup
  chmod +x $STAGE3_DIR/setup
  chroot $STAGE3_DIR /setup
  rm $STAGE3_DIR/setup
fi

